"""Created Following Tables: User, Post, Country, Country_Subdivision, Country_Subdivision_Type, City, Currency

Revision ID: 3467a66ec4a3
Revises: 
Create Date: 2019-08-30 20:21:33.536671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3467a66ec4a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('code2', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('phonecode', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('easting', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('northing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_subdivision_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('firstName', sa.String(length=256), nullable=True),
    sa.Column('lastName', sa.String(length=256), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('lastLoginDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('country_subdivision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('easting', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('northing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('countrySubdivisionType_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['countrySubdivisionType_id'], ['country_subdivision_type.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('easting', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('northing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('countrySubdivision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['countrySubdivision_id'], ['country_subdivision.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('country_subdivision')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('currency')
    op.drop_table('country_subdivision_type')
    op.drop_table('country')
    # ### end Alembic commands ###
