"""Created Tables: Activity, Activity Type, EquipmentType, AccommodationType, and TransportType.

Revision ID: 45442016e7b8
Revises: e6bd98981055
Create Date: 2019-08-31 16:22:38.711663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45442016e7b8'
down_revision = 'e6bd98981055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('activityType_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activityType_id'], ['activity_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('transport_type')
    op.drop_table('equipment_type')
    op.drop_table('activity_type')
    op.drop_table('accommodation_type')
    # ### end Alembic commands ###
