"""Users, Posts, Countries, States, and Places tables created.

Revision ID: 9b8f76f37141
Revises: 
Create Date: 2019-08-23 22:55:37.190863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8f76f37141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('easting', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('northing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('firstName', sa.String(length=256), nullable=True),
    sa.Column('lastName', sa.String(length=256), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('lastLoginDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('country_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('easting', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('northing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('easting', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('northing', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('countrystate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['countrystate_id'], ['country_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('country_state')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('country')
    # ### end Alembic commands ###
