"""Updated City Table to hold a city Code.

Revision ID: e6bd98981055
Revises: 3467a66ec4a3
Create Date: 2019-08-30 20:41:44.696422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bd98981055'
down_revision = '3467a66ec4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'code')
    # ### end Alembic commands ###
